### ISSUE TITLE
option to skip good mentions

### ISSUE THREAD

**Issue by marcelloh** [nikolaydubina/vertfn#8]
a.k.a. the green output :-)

Because doing this on a bigger project  will probably mention a lot of green lines (unnecessary)

**Comment by nikolaydubina** [comment]
this is default. without `--verbose` only errors show up

**Comment by marcelloh** [comment]
How could a user have guessed that, there is no example or mention in the readme :-)

**Comment by nikolaydubina** [comment]
`vertfn -h`!
